### ISSUE TITLE
チュートリアルのドキュメントをtutorial_docsに記載:sphinxで作成

### ISSUE THREAD

**Issue by hrsano645** [py-suruga/pycon-jp-2020-tutorial#8]
必要なドキュメントは issue #5 の各項目に、参加前準備用も必要

- [x] prepare: Pythonのインストール方法, 資料のDL方法を記載 -> https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658009067 , https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658009714
    - [x] vscode_and_liveshare: vscodeのセットアップ, liveshareの使い方: https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658009714
- [x] slackbot: slackbotの実装方法: https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658026032
- [x] pytest: 実装したslackbotのテストをpytestで書く: https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658028496
- [x] sphinx-autodoc: slackbotで実装したbotの実態（各APIから結果の生成）をドキュメントとして残す: https://github.com/py-suruga/pycon-jp-2020-tutorial/issues/5#issuecomment-658806008

**Comment by hrsano645** [comment]
sphinxのプロジェクト生成時のログ

```powershell
PS C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial> sphinx-quickstart
Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: 
[Interrupted.]
PS C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial> cd .\tutorial_docs\
PS C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs> sphinx-quickstart.exe
Welcome to the Sphinx 3.1.2 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: n

The project name will occur in several places in the built documentation.
> Project name: pycon-jp-2020-tutorial-development-slackbot
> Author name(s): Py-Suruga, Unagi-py, Hiroshi sano
> Project release []: 2020.07.24

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language.
> Project language [en]: ja

Creating file C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs\conf.py.  
Creating file C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs\index.rst.
Creating file C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs\Makefile. 
Creating file C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs\make.bat. 

Finished: An initial directory structure has been created.

You should now populate your master file C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs\index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.

PS C:\Users\hiroshi\Documents\workspace\personal\pycon-jp-2020-tutorial\tutorial_docs> 
```

**Comment by hrsano645** [comment]
一通りのファイルを用意できたので、詳細を詰めていく。

**Comment by hrsano645** [comment]
注釈的な情報を乗せたいときのディレクティブ

https://sphinx-users.jp/gettingstarted/directives.html#id10

noteを使えばよさそう

**Comment by hrsano645** [comment]
todo ディレクティブも利用して、TODO管理しておく

https://www.sphinx-doc.org/ja/master/usage/extensions/todo.html

**Comment by hrsano645** [comment]
ここのPRでTODOすべて潰せたので、一通りの必要なものを用意できたとしてissueクローズです。
https://github.com/py-suruga/pycon-jp-2020-tutorial/pull/28
